### ISSUE TITLE
Link the course codes to kDB syllabi

### ISSUE THREAD

**Issue by yudukikun5120** [manaba-enhanced-for-tsukuba/manaba-enhanced#518]
## Motivation

Adding the link to the syllabus of the course will make it easier for students to find the syllabus.

This feature was originally provided by the repository [manaba2kdb](https://github.com/smasato/manaba2kdb). We can **modify** and **distribute** the feature as the repository is under the MIT license.

**Comment by mkobayashime** [comment]
@yudukikun5120 
I haven't been included this feature until now in respect for the preceding extension, despite we can use the code legally of course, and I have not plan to do that.

**Comment by yudukikun5120** [comment]
@mkobayashime I know that point, There needed both agreements (direct licensing except for the MIT license) at first.
